name: deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "^17"
      - uses: pnpm/action-setup@v2
        with:
          version: "^6"

      - run: make build

      - uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: ./public
          clean: true